<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>md</string>
		<string>mdown</string>
	</array>
	<key>name</key>
	<string>Didaktische Jahresplanung</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(if|while|for|return)\b</string>
			<key>name</key>
			<string>keyword.control.untitled</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*#\s+</string>
			<key>end</key>
			<string>\n</string>
			<key>name</key>
			<string>markup.heading.1.title.lernfeld</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(^\s*##\s*.*)$</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>markup.heading.2.title.lernsituation</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=^##\s+)</string>
			<key>name</key>
			<string>lernsituation</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^\s*\*.*Fach.*kompetenz</string>
					<key>end</key>
					<string>^\n|(?=^\*)|(?=^\s*$)</string>
					<key>name</key>
					<string>markup.list.fachkompetenz</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>^\s*\*.*(Selbst|Methode|Sozial).*kompetenz</string>
					<key>end</key>
					<string>^\n|(?=^\*)|(?=^\s*$)</string>
					<key>name</key>
					<string>markup.list.sms_kompetenz</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>^\s*\*.*(Didaktik|Orga|Verantwortlich).*</string>
					<key>end</key>
					<string>^\n|(?=^\*)|(?=^\s*$)</string>
					<key>name</key>
					<string>markup.list.did_orga</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>^\s*\*.*(Verknüpfung)</string>
					<key>end</key>
					<string>^\n|(?=^\*)|(?=^\s*$)</string>
					<key>name</key>
					<string>markup.list.verknuepfung</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>^\s*\*.*(Benotung)</string>
					<key>end</key>
					<string>^\n|(?=^\*)|(?=^\s*$)</string>
					<key>name</key>
					<string>markup.list.benotung</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>^\s*\*.*(Stunde|Dauer|Länge)</string>
					<key>end</key>
					<string>^\n|(?=^\*)|(?=^\s*$)</string>
					<key>name</key>
					<string>markup.list.stunden</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scope</key>
	<string>dj</string>
	<key>scopeName</key>
	<string>source.dj</string>
	<key>uuid</key>
	<string>C8620965-0689-48AA-8368-9C710F05C10D</string>
</dict>
</plist>
